import type { Metadata } from "next";
import "../css/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Quang",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[1280px] m-auto">
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
